version: "3"
services:
  mysqldb:
    container_name: mysql-shop
    image: mysql
    ports:
      - "3306:3306"  # по желанию — если нужен доступ к БД извне
    environment:
      MYSQL_DATABASE: gartenshop
      MYSQL_ROOT_PASSWORD: chemnitz2023
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p'chemnitz2023'"]
      timeout: 20s
      retries: 10

  spring-boot-app:
    container_name: spring-online-shop
    image: gartenshop.1.0
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8088"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_DB_NAME: gartenshop
      MYSQL_USER: root
      MYSQL_PASSWORD: chemnitz2023
      MYSQL_PORT: 3306
    depends_on:
      mysqldb:
        condition: service_healthy
