version: "3"
services:
  spring-boot-app:
    container_name: spring-online-shop
    image: gartenshop.1.0
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
