version: "3"
services:
  mysqldb:
    container_name: mysql-shop
    image: mysql
    ports:
      - "23306:3306"
    environment:
      MYSQL_DATABASE: gartenshop
      MYSQL_ROOT_PASSWORD: chemnitz2023
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p'chemnitz2023'"]
      timeout: 20s
      retries: 10

  spring-boot-app:
    container_name: spring-online-shop
    image: gartenshop.1.0
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18088:8088"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    depends_on:
      mysqldb:
        condition: service_healthy